# 改自 1panel 面板中的模板
version: "3.8"
services:
  aria2-pro:
    container_name: aria2-pro
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK_SET=002
      - RPC_SECRET=adcb48dac7609c8f4b3b
      - RPC_PORT=6800
      - LISTEN_PORT=6888
    image: p3terx/aria2-pro
    ports:
      - 6800:6800
      - 6888:6888
      - 6888:6888/udp
    networks:
      - 1panel-network
    volumes:
      - /data/aria2/temp_data:/data/aria2/temp_data
      - /root/docker/aria2-config:/config
      - /www/wwwroot/aria2-downloads:/www/wwwroot/aria2-downloads
      - /data/cloudreve/uploads:/cloudreve/uploads

  # AriaNg:
  #   container_name: ariang
  #   image: p3terx/ariang
  #   command: --port 6880 --ipv6
  #   ports:
  #     - "6880:6880"
  #   networks:
  #     - 1panel-network
  #   restart: unless-stopped
  #   logging:
  #     driver: json-file
  #     options:
  #       max-size: 1m

  cloudreve:
    container_name: cloudreve
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    image: cloudreve/cloudreve:3.8.3
    labels:
      createdBy: Apps
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - "${HOST_IP}:${PANEL_APP_PORT_HTTP}:5212"
    networks:
      - 1panel-network
    restart: unless-stopped
    volumes:
      - /data/aria2/temp_data:/data/aria2/temp_data
      - /data/cloudreve/uploads:/cloudreve/uploads
      - /data/cloudreve/conf.ini:/cloudreve/conf.ini
      - /data/cloudreve/cloudreve.db:/cloudreve/cloudreve.db
      - /data/cloudreve/avatar:/cloudreve/avatar
# 离线下载节点RPC 服务器地址： http://<aria2-pro docker内网 IP>:6800/，路径：/www/wwwroot/aria2-downloads
networks:
  1panel-network:
    external: true