# 改自 1panel 面板中的模板
version: "3.8"
services:
  aria2-pro:
    container_name: aria2-pro
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK_SET=002
      - RPC_SECRET=<token>
      - RPC_PORT=6800
      - LISTEN_PORT=6888
    image: p3terx/aria2-pro
    ports:
      - 6800:6800
      - 6888:6888
      - 6888:6888/udp
    volumes:
      - /www/wwwroot/aria2-config:/config
      - /www/wwwroot/aria2-downloads:/www/wwwroot/aria2-downloads
      - /www/wwwroot/cloudreve/uploads:/cloudreve/uploads

  # AriaNg:
  #   container_name: ariang
  #   image: p3terx/ariang
  #   command: --port 6880 --ipv6
  #   ports:
  #     - "6880:6880"
  #   networks:
  #     - 1panel-network
  #   restart: unless-stopped
  #   logging:
  #     driver: json-file
  #     options:
  #       max-size: 1m

  cloudreve:
    container_name: cloudreve
    # deploy:
    #   resources:
    #     limits:
    #       cpus: ${CPUS}
    #       memory: ${MEMORY_LIMIT}
    image: cloudreve/cloudreve:3.8.3
    # labels:
    #   createdBy: Apps
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - "5212:5212"
    restart: unless-stopped
    volumes:
      - /www/wwwroot/aria2-downloads:/www/wwwroot/aria2-downloads
      - /www/wwwroot/cloudreve/uploads:/cloudreve/uploads
      - /www/wwwroot/cloudreve/conf.ini:/cloudreve/conf.ini
      - /www/wwwroot/cloudreve/cloudreve.db:/cloudreve/cloudreve.db
      - /www/wwwroot/cloudreve/avatar:/cloudreve/avatar
# 离线下载节点RPC 服务器地址： http://<aria2-pro docker内网 IP>:6800/，路径：/www/wwwroot/aria2-downloads
# networks:
#   1panel-network:
#     external: true